### ISSUE TITLE
Contribute to maintained fork

### ISSUE THREAD

**Issue by jschwartzenberg** [jordidg/cntlm#1]
Hi @jordidg! Did you consider rebasing this and creating a PR against https://github.com/versat/cntlm which is still maintained? IPv6 support would be really great!

**Comment by jschwartzenberg** [comment]
Just to let you know, I've created a PR based on your work.  feature-wise it's working quite well both IPv4 and IPv6 are working in parallel with a few small changes. I hope to finish it off soon and get it included with the main branch.
https://github.com/versat/cntlm/pull/8

**Comment by jordidg** [comment]
Hi @jschwartzenberg, thanks for the work to include it upstream.
I'm no longer using cntlm, but I'm glad to know my patches were useful to somebody.
